In [29]:
import pandas as pd
import numpy as np


In [30]:
!wget -O ChurnData.csv https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-ML0101EN-SkillsNetwork/labs/Module%203/data/ChurnData.csv

--2023-10-19 04:00:32--  https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-ML0101EN-SkillsNetwork/labs/Module%203/data/ChurnData.csv
Resolving cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud (cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud)... 169.63.118.104
Connecting to cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud (cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud)|169.63.118.104|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 35943 (35K) [text/csv]
Saving to: ‘ChurnData.csv’

ChurnData.csv       100%[===================>]  35.10K  --.-KB/s    in 0.001s  

2023-10-19 04:00:33 (26.6 MB/s) - ‘ChurnData.csv’ saved [35943/35943]



In [31]:
df = pd.read_csv("ChurnData.csv")

In [32]:
df.head()

tenure   age  address  income   ed  employ  equip  callcard  wireless  \
0    11.0  33.0      7.0   136.0  5.0     5.0    0.0       1.0       1.0   
1    33.0  33.0     12.0    33.0  2.0     0.0    0.0       0.0       0.0   
2    23.0  30.0      9.0    30.0  1.0     2.0    0.0       0.0       0.0   
3    38.0  35.0      5.0    76.0  2.0    10.0    1.0       1.0       1.0   
4     7.0  35.0     14.0    80.0  2.0    15.0    0.0       1.0       0.0   

   longmon  ...  pager  internet  callwait  confer  ebill  loglong  logtoll  \
0     4.40  ...    1.0       0.0       1.0     1.0    0.0    1.482    3.033   
1     9.45  ...    0.0       0.0       0.0     0.0    0.0    2.246    3.240   
2     6.30  ...    0.0       0.0       0.0     1.0    0.0    1.841    3.240   
3     6.05  ...    1.0       1.0       1.0     1.0    1.0    1.800    3.807   
4     7.10  ...    0.0       0.0       1.0     1.0    0.0    1.960    3.091   

   lninc  custcat  churn  
0  4.913      4.0    1.0  
1  3.497      1.0    1.0  
2  3.401      3.0    0.0  
3  4.331      4.0    0.0  
4  4.382      3.0    0.0  

[5 rows x 28 columns]

In [33]:
x = df[['tenure', 'age', 'address', 'income', 'ed', 'employ', 'equip', 'callcard', 'wireless']]
y = df[['churn']]

In [34]:
x.head()

tenure   age  address  income   ed  employ  equip  callcard  wireless
0    11.0  33.0      7.0   136.0  5.0     5.0    0.0       1.0       1.0
1    33.0  33.0     12.0    33.0  2.0     0.0    0.0       0.0       0.0
2    23.0  30.0      9.0    30.0  1.0     2.0    0.0       0.0       0.0
3    38.0  35.0      5.0    76.0  2.0    10.0    1.0       1.0       1.0
4     7.0  35.0     14.0    80.0  2.0    15.0    0.0       1.0       0.0

In [35]:
y.head()

churn
0    1.0
1    1.0
2    0.0
3    0.0
4    0.0

In [36]:
y['churn'] = y['churn'].astype("int")

/home/jupyterlab/conda/envs/python/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [37]:
y['churn'].dtype

dtype('int64')

In [38]:
y['churn'].head()

0    1
1    1
2    0
3    0
4    0
Name: churn, dtype: int64

In [39]:
x = np.asanyarray(x)
y = np.asanyarray(y)

In [40]:
x[:5]

array([[ 11.,  33.,   7., 136.,   5.,   5.,   0.,   1.,   1.],
       [ 33.,  33.,  12.,  33.,   2.,   0.,   0.,   0.,   0.],
       [ 23.,  30.,   9.,  30.,   1.,   2.,   0.,   0.,   0.],
       [ 38.,  35.,   5.,  76.,   2.,  10.,   1.,   1.,   1.],
       [  7.,  35.,  14.,  80.,   2.,  15.,   0.,   1.,   0.]])

In [41]:
y[:5]

array([[1],
       [1],
       [0],
       [0],
       [0]])

In [42]:
len(x)

200

In [43]:
from sklearn.model_selection  import train_test_split
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size = 0.2, random_state = 21)

In [48]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
train_x= sc.fit_transform(train_x)

In [49]:
train_x

array([[-0.7757106 ,  2.15058684,  1.64961228, ..., -0.81649658,
        -1.52752523, -0.64492573],
       [-1.36911923,  0.45554303, -0.47077688, ..., -0.81649658,
         0.65465367, -0.64492573],
       [-1.18653196, -1.31654824, -0.87466053, ...,  1.22474487,
        -1.52752523, -0.64492573],
       ...,
       [ 1.64357072,  1.14897004,  1.14475772, ..., -0.81649658,
         0.65465367, -0.64492573],
       [-1.27782559, -0.46902633,  0.23601951, ..., -0.81649658,
         0.65465367, -0.64492573],
       [-1.04959151,  1.76534961,  0.1350486 , ...,  1.22474487,
         0.65465367, -0.64492573]])

In [52]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(C = 0.01, solver = 'liblinear')

In [53]:
clf.fit(train_x, train_y)

/home/jupyterlab/conda/envs/python/lib/python3.7/site-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


LogisticRegression(C=0.01, solver='liblinear')

In [58]:
clf.predict(train_x)[:10]

array([0, 0, 1, 1, 0, 0, 1, 0, 0, 0])

In [57]:
train_y[:10]

array([[0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0]])

In [59]:
test_x = sc.transform(test_x)

In [60]:
pred_y = clf.predict(test_x)

In [61]:
pred_y

array([1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1])

In [64]:
test_y.ravel()

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1])

In [68]:
from sklearn.metrics import confusion_matrix, classification_report

In [67]:
confusion_matrix(test_y, pred_y)

array([[21,  9],
       [ 2,  8]])

In [70]:
print(classification_report(test_y, pred_y))

              precision    recall  f1-score   support

           0       0.91      0.70      0.79        30
           1       0.47      0.80      0.59        10

    accuracy                           0.73        40
   macro avg       0.69      0.75      0.69        40
weighted avg       0.80      0.72      0.74        40



In [71]:
train_y.shape

(160, 1)

In [72]:
print(classification_report(train_y.ravel(), clf.predict(train_x)))

              precision    recall  f1-score   support

           0       0.87      0.76      0.81       112
           1       0.56      0.73      0.64        48

    accuracy                           0.75       160
   macro avg       0.72      0.74      0.72       160
weighted avg       0.78      0.75      0.76       160



In [73]:
confusion_matrix(train_y.ravel(), clf.predict(train_x))

array([[85, 27],
       [13, 35]])

In [78]:
pred_y_prob = clf.predict_proba(test_x)

In [79]:
from sklearn.metrics import log_loss
log_loss(test_y, pred_y_prob)

0.5751658012938381

In [81]:
pred_y_prob[:5]

array([[0.49720876, 0.50279124],
       [0.68179491, 0.31820509],
       [0.48149826, 0.51850174],
       [0.66947198, 0.33052802],
       [0.73045348, 0.26954652]])