In [2]:
!wget -O cell_samples.csv https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-ML0101EN-SkillsNetwork/labs/Module%203/data/cell_samples.csv

--2023-10-19 04:28:34--  https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-ML0101EN-SkillsNetwork/labs/Module%203/data/cell_samples.csv
Resolving cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud (cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud)... 169.63.118.104
Connecting to cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud (cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud)|169.63.118.104|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 19975 (20K) [text/csv]
Saving to: ‘cell_samples.csv’

cell_samples.csv    100%[===================>]  19.51K  --.-KB/s    in 0.001s  

2023-10-19 04:28:34 (35.9 MB/s) - ‘cell_samples.csv’ saved [19975/19975]



In [22]:
import pandas as pd


In [23]:
df = pd.read_csv('cell_samples.csv')

In [24]:
df.head()

ID  Clump  UnifSize  UnifShape  MargAdh  SingEpiSize BareNuc  \
0  1000025      5         1          1        1            2       1   
1  1002945      5         4          4        5            7      10   
2  1015425      3         1          1        1            2       2   
3  1016277      6         8          8        1            3       4   
4  1017023      4         1          1        3            2       1   

   BlandChrom  NormNucl  Mit  Class  
0           3         1    1      2  
1           3         2    1      2  
2           3         1    1      2  
3           3         7    1      2  
4           3         1    1      2

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 699 entries, 0 to 698
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   ID           699 non-null    int64 
 1   Clump        699 non-null    int64 
 2   UnifSize     699 non-null    int64 
 3   UnifShape    699 non-null    int64 
 4   MargAdh      699 non-null    int64 
 5   SingEpiSize  699 non-null    int64 
 6   BareNuc      699 non-null    object
 7   BlandChrom   699 non-null    int64 
 8   NormNucl     699 non-null    int64 
 9   Mit          699 non-null    int64 
 10  Class        699 non-null    int64 
dtypes: int64(10), object(1)
memory usage: 60.2+ KB


In [26]:
import numpy as np

In [30]:
df = df[pd.to_numeric(df['BareNuc'], errors = 'coerce').notnull()]

In [31]:
df.shape

(683, 11)

In [32]:
x = df[['ID', 'Clump', 'UnifSize', 'UnifShape', 'MargAdh', 'SingEpiSize', 'BareNuc', 'NormNucl', 'Mit']].values
y = df['Class'].values

In [36]:
from sklearn.model_selection import train_test_split
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size =0.25, random_state = 21)

In [38]:
train_x.shape,  train_y.shape

((512, 9), (512,))

In [39]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
train_x = sc.fit_transform(train_x)

In [42]:
from sklearn.svm import SVC
clf = SVC(kernel = 'rbf')

In [43]:
clf.fit(train_x, train_y)

SVC()

In [44]:
test_x = sc.transform(test_x)
pred_y = clf.predict(test_x)

In [45]:
pred_y[:5]

array([4, 4, 2, 2, 2])

In [47]:
test_y[:5]

array([4, 4, 2, 2, 2])

In [53]:
unq = len(np.unique(test_y))

In [55]:
unq

2

In [56]:
from sklearn.metrics import jaccard_score
jaccard_score(pred_y, test_y,pos_label = unq )

0.954954954954955

In [57]:
from sklearn.metrics import confusion_matrix
confusion_matrix(test_y, pred_y)

array([[106,   2],
       [  3,  60]])